<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="16" started-at="2017-04-08T22:01:39Z" finished-at="2017-04-08T22:01:39Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="16" started-at="2017-04-08T22:01:39Z" finished-at="2017-04-08T22:01:39Z">
      <class name="testcases.TC002_LoginFailure">
        <test-method status="PASS" signature="beforeSuite()[pri:0, instance:testcases.TC002_LoginFailure@11be3c5]" name="beforeSuite" is-config="true" duration-ms="1066" started-at="2017-04-09T03:31:38Z" finished-at="2017-04-09T03:31:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeSuite -->
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:testcases.TC002_LoginFailure@11be3c5]" name="beforeTest" is-config="true" duration-ms="0" started-at="2017-04-09T03:31:39Z" finished-at="2017-04-09T03:31:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="PASS" signature="setData()[pri:0, instance:testcases.TC002_LoginFailure@11be3c5]" name="setData" is-config="true" duration-ms="0" started-at="2017-04-09T03:31:39Z" finished-at="2017-04-09T03:31:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setData -->
        <test-method status="SKIP" signature="login(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:testcases.TC002_LoginFailure@11be3c5]" name="login" duration-ms="0" started-at="2017-04-09T03:31:39Z" data-provider="fethData" finished-at="2017-04-09T03:31:39Z">
          <exception class="org.testng.TestNGException">
            <message>
              <![CDATA[
Method public void testcases.TC002_LoginFailure.login(java.lang.String,java.lang.String,java.lang.String) requires a @DataProvider named : fethData]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestNGException: 
Method public void testcases.TC002_LoginFailure.login(java.lang.String,java.lang.String,java.lang.String) requires a @DataProvider named : fethData
	at org.testng.internal.Parameters.findDataProvider(Parameters.java:262)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:418)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1269)
	at org.testng.internal.Invoker.createParameters(Invoker.java:985)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1075)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestNGException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:testcases.TC002_LoginFailure@11be3c5]" name="afterTest" is-config="true" duration-ms="0" started-at="2017-04-09T03:31:39Z" finished-at="2017-04-09T03:31:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
        <test-method status="PASS" signature="afterSuite()[pri:0, instance:testcases.TC002_LoginFailure@11be3c5]" name="afterSuite" is-config="true" duration-ms="443" started-at="2017-04-09T03:31:39Z" finished-at="2017-04-09T03:31:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuite -->
      </class> <!-- testcases.TC002_LoginFailure -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
